- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Files/StorageTests.Exceptions.RetrieveFile.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Files/StorageTests.Logic.RetrieveFile.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Files/StorageTests.Validations.CreateFile.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Files/StorageTests.Validations.RetrieveFile.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Files/StorageTests.cs
- ISL.Providers.Storages.AzureBlobStorage/Services/Foundations/Files/StorageService.Validations.cs
- ISL.Providers.Storages.AzureBlobStorage/Services/Foundations/Files/StorageService.cs
> FOUNDATIONS: Azure Storage RetrieveFile

- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Files/StorageTests.Exceptions.DeleteFile.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Files/StorageTests.Exceptions.RetrieveFile.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Files/StorageTests.Logic.DeleteFile.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Files/StorageTests.Logic.RetrieveFile.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Files/StorageTests.Validations.CreateFile.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Files/StorageTests.Validations.DeleteFile.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Files/StorageTests.Validations.RetrieveFile.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Files/StorageTests.cs
- ISL.Providers.Storages.AzureBlobStorage/Services/Foundations/Files/StorageService.Validations.cs
- ISL.Providers.Storages.AzureBlobStorage/Services/Foundations/Files/StorageService.cs
> FOUNDATIONS: Azure Storage DeleteFile

- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Files/StorageTests.Exceptions.CreateFile.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Files/StorageTests.Exceptions.DeleteFile.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Files/StorageTests.Exceptions.ListFilesInContainer.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Files/StorageTests.Exceptions.RetrieveFile.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Files/StorageTests.Logic.DeleteFile.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Files/StorageTests.Logic.ListFilesInContainer.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Files/StorageTests.Logic.RetrieveFile.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Files/StorageTests.Validations.CreateFile.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Files/StorageTests.Validations.DeleteFile.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Files/StorageTests.Validations.ListFilesInContainer.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Files/StorageTests.Validations.RetrieveFile.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Files/StorageTests.cs
- ISL.Providers.Storages.AzureBlobStorage/Services/Foundations/Files/StorageService.Exceptions.cs
- ISL.Providers.Storages.AzureBlobStorage/Services/Foundations/Files/StorageService.Validations.cs
- ISL.Providers.Storages.AzureBlobStorage/Services/Foundations/Files/StorageService.cs
> FOUNDATIONS: Aazure Storage ListFilesInContainer

- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Files/StorageTests.Exceptions.GetDownloadLink.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Files/StorageTests.Logic.GetDownloadLink.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Files/StorageTests.Validations.GetDownloadLink.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Files/StorageTests.cs
- ISL.Providers.Storages.AzureBlobStorage/Brokers/Storages/Blobs/BlobStorageBroker.cs
- ISL.Providers.Storages.AzureBlobStorage/Brokers/Storages/Blobs/IBlobStorageBroker.cs
- ISL.Providers.Storages.AzureBlobStorage/Services/Foundations/Files/StorageService.Exceptions.cs
- ISL.Providers.Storages.AzureBlobStorage/Services/Foundations/Files/StorageService.Validations.cs
- ISL.Providers.Storages.AzureBlobStorage/Services/Foundations/Files/StorageService.cs
> FOUNDATIONS: Azure Storage GetDownloadLink

- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Files/StorageTests.Exceptions.CreateContainer.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Files/StorageTests.Logic.CreateContainer.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Files/StorageTests.Validations.CreateContainer.cs
- ISL.Providers.Storages.AzureBlobStorage/Services/Foundations/Files/StorageService.Validations.cs
- ISL.Providers.Storages.AzureBlobStorage/Services/Foundations/Files/StorageService.cs
> FOUNDATIONS: Azure Storage CreateContainer

- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Exceptions.CreateFile.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Logic.CreateFile.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.cs
- ISL.Providers.Storages.AzureBlobStorage/ISL.Providers.Storages.AzureBlobStorage.csproj
- ISL.Providers.Storages.AzureBlobStorage/Models/Providers/Exceptions/AzureBlobStorageProviderDependencyException.cs
- ISL.Providers.Storages.AzureBlobStorage/Models/Providers/Exceptions/AzureBlobStorageProviderDependencyValidationException.cs
- ISL.Providers.Storages.AzureBlobStorage/Models/Providers/Exceptions/AzureBlobStorageProviderServiceException.cs
- ISL.Providers.Storages.AzureBlobStorage/Models/Providers/Exceptions/AzureBlobStorageProviderValidationException.cs
- ISL.Providers.Storages.AzureBlobStorage/Providers/AzureBlobStorage/AzureBlobStorageProvider.cs
- ISL.Providers.Storages.AzureBlobStorage/Providers/AzureBlobStorage/IAzureBlobStorageProvider.cs
> PROVIDERS: AzureBlobStorage InsertFile

- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Exceptions.RetrieveFile.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Logic.RetrieveFile.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.cs
- ISL.Providers.Storages.AzureBlobStorage/Providers/AzureBlobStorage/AzureBlobStorageProvider.cs
> PROVIDERS: AzureBlobStorage RetrieveFile

- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Files/StorageTests.Exceptions.CreateDirectorySasToken.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Files/StorageTests.Logic.CreateDirectorySasToken.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Files/StorageTests.Logic.GetDownloadLink.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Files/StorageTests.Validations.CreateDirectorySasToken.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Files/StorageTests.cs
- ISL.Providers.Storages.AzureBlobStorage/Brokers/Storages/Blobs/BlobStorageBroker.cs
- ISL.Providers.Storages.AzureBlobStorage/Brokers/Storages/Blobs/IBlobStorageBroker.cs
- ISL.Providers.Storages.AzureBlobStorage/ISL.Providers.Storages.AzureBlobStorage.csproj
- ISL.Providers.Storages.AzureBlobStorage/Models/AzureBlobStoreConfigurations.cs
- ISL.Providers.Storages.AzureBlobStorage/Services/Foundations/Files/IStorageService.cs
- ISL.Providers.Storages.AzureBlobStorage/Services/Foundations/Files/StorageService.Validations.cs
- ISL.Providers.Storages.AzureBlobStorage/Services/Foundations/Files/StorageService.cs
> FOUNDATIONS: Storages CreateDirectorySasToken

- ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.Exceptions.ListContainer.cs
- ISL.Providers.Storages.Abstractions/IStorageOperations.cs
- ISL.Providers.Storages.Abstractions/StorageAbstractionProvider.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Logic.ListFilesInContainer.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTestsExceptions.ListFilesInContainer.cs
- ISL.Providers.Storages.AzureBlobStorage/Providers/AzureBlobStorage/AzureBlobStorageProvider.cs
> PROVIDERS: AzureBlobStorage ListFilesInContainer

- ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.Exceptions.CreateAndAssignAccessPoliciesToContainerAsync.cs
- ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.Exceptions.CreateFile.cs
- ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.Exceptions.DeleteFile.cs
- ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.Exceptions.GetAccessToken.cs
- ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.Exceptions.GetDownloadLink.cs
- ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.Exceptions.ListContainer.cs
- ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.Logic.CreateAndAssignAccessPoliciesToContainerAsync.cs
- ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.cs
- ISL.Providers.Storages.Abstractions/IStorageOperations.cs
- ISL.Providers.Storages.Abstractions/Models/Exceptions/StorageProviderDependencyValidationException.cs
- ISL.Providers.Storages.Abstractions/StorageAbstractionProvider.cs
- ISL.Providers.Storages.Abstractions/StrogareAbstractionProvider.Exceptions.cs
- ISL.Providers.Storages.AzureBlobStorage/Providers/AzureBlobStorage/AzureBlobStorageProvider.cs
> PROVIDERS: Azure Storage Abstraction - CreateAndAssignAccessPoliciesToContainerAsync

- ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.Exceptions.CreateAndAssignAccessPoliciesToContainerAsync.cs
- ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.Exceptions.RemoveAccessPoliciesFromContainerAsync.cs
- ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.Logic.RemoveAccessPoliciesFromContainerAsync.cs
- ISL.Providers.Storages.Abstractions/IStorageOperations.cs
- ISL.Providers.Storages.Abstractions/StorageAbstractionProvider.cs
- ISL.Providers.Storages.AzureBlobStorage/Providers/AzureBlobStorage/AzureBlobStorageProvider.cs
> PROVIDERS: StorageAbstraction - RemoveAccessPoliciesFromContainerAsync

- ISL.Providers.Storages.Abstractions/IStorageOperations.cs
- ISL.Providers.Storages.Abstractions/StorageAbstractionProvider.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Exceptions.CreateDirectorySasToken.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Logic.CreateDirectorySasToken.cs
- ISL.Providers.Storages.AzureBlobStorage/Providers/AzureBlobStorage/AzureBlobStorageProvider.cs
> PROVDERS: AzureBlobStorage CreateDirectorySasToken

- ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.Exceptions.CreateFolderInContainer.cs
- ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.Logic.CreateFolderInContainer.cs
- ISL.Providers.Storages.Abstractions/IStorageOperations.cs
- ISL.Providers.Storages.Abstractions/StorageAbstractionProvider.cs
- ISL.Providers.Storages.AzureBlobStorage/Providers/AzureBlobStorage/AzureBlobStorageProvider.cs
> PROVIDERS: StorageAbstraction - CreateFolderInContainer

- ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.Exceptions.RetrieveAllAccessPoliciesFromContainerAsync.cs
- ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.Logic.RetrieveAllAccessPoliciesFromContainerAsync.cs
- ISL.Providers.Storages.Abstractions/IStorageOperations.cs
- ISL.Providers.Storages.Abstractions/StorageAbstractionProvider.cs
- ISL.Providers.Storages.AzureBlobStorage/Providers/AzureBlobStorage/AzureBlobStorageProvider.cs
> PROVIDERS: StorageAbstraction - RetrieveAllAccessPoliciesFromContainer

- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Exceptions.CreateFolder.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Logic.CreateFolder.cs
- ISL.Providers.Storages.AzureBlobStorage/Providers/AzureBlobStorage/AzureBlobStorageProvider.cs
> PROVIDERS: AzureBlobStorage CreateFolderInContainer

- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Exceptions.RetrieveAllContainers.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Logic.RetrieveAllContainers.cs
- ISL.Providers.Storages.AzureBlobStorage/Providers/AzureBlobStorage/AzureBlobStorageProvider.cs
> PROVIDERS: AzureBlobStorage RetrieveAllContainers

- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Storages/StorageTests.Exceptions.DeleteContainer.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Storages/StorageTests.Logic.DeleteContainer.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Storages/StorageTests.Validations.DeleteContainer.cs
- ISL.Providers.Storages.AzureBlobStorage/Brokers/Storages/Blobs/BlobStorageBroker.cs
- ISL.Providers.Storages.AzureBlobStorage/Brokers/Storages/Blobs/IBlobStorageBroker.cs
- ISL.Providers.Storages.AzureBlobStorage/Services/Foundations/Storages/IStorageService.cs
- ISL.Providers.Storages.AzureBlobStorage/Services/Foundations/Storages/StorageService.cs
> FOUNDATIONS: Storages DeleteContainerAsync

- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Exceptions.DeleteContainer.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Logic.DeleteContainer.cs
- ISL.Providers.Storages.AzureBlobStorage/Providers/AzureBlobStorage/AzureBlobStorageProvider.cs
> PROVIDERS: AzureBlobStorage DeleteContainer

- ISL.Providers.Storages.Abstractions/IStorageOperations.cs
- ISL.Providers.Storages.Abstractions/StorageAbstractionProvider.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Acceptance/AzureBlobStorageProviderTests.CreateContainer.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Acceptance/AzureBlobStorageProviderTests.ListFilesInContainer.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Acceptance/AzureBlobStorageProviderTests.cs
> ACCEPTANCE: AzureBlobStorage CreateContainer

- ISL.Providers.Storages.AzureBlobStorage.Tests.Acceptance/AzureBlobStorageProviderTests.ListFilesInContainer.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Acceptance/AzureBlobStorageProviderTests.cs
> ACCEPTANCE: AzureBlobStorage ListFilesInContainer

- ISL.Providers.Storages.AzureBlobStorage.Tests.Acceptance/AzureBlobStorageProviderTests.CreateAndAssignAccessPolicies.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Acceptance/AzureBlobStorageProviderTests.RetrieveAllAccessPoliciesFromContainer.cs
> ACCEPTANCE: AzureBlobStorage RetrieveAllAccessPolicies

- ISL.Providers.Storages.AzureBlobStorage.Tests.Acceptance/AzureBlobStorageProviderTests.CreateAndAssignAccessPolicies.cs
> ACCEPTANCE: AzureBlobStorage CreateAndAssignAccessPolicies

- ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.Exceptions.RetrieveAccessPolicyByNameAsync.cs
- ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.Logic.RetrieveAccessPolicyByName.cs
- ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.cs
- ISL.Providers.Storages.Abstractions/IStorageOperations.cs
- ISL.Providers.Storages.Abstractions/StorageAbstractionProvider.cs
- ISL.Providers.Storages.Abstractions/StrogareAbstractionProvider.Exceptions.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Exceptions.RetrieveAccessPolicyByName.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Logic.RetrieveAccessPolicyByName.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.cs
- ISL.Providers.Storages.AzureBlobStorage/Providers/AzureBlobStorage/AzureBlobStorageProvider.cs
> PROVIDERS: AzureBlobStorage RetrieveAccessPolicyByName

- ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.Exceptions.RetrieveAllAccessPoliciesAsync.cs
- ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.Logic.RetrieveAllAccessPoliciesAsync.cs
- ISL.Providers.Storages.Abstractions/IStorageOperations.cs
- ISL.Providers.Storages.Abstractions/StorageAbstractionProvider.cs
- ISL.Providers.Storages.Abstractions/StrogareAbstractionProvider.Exceptions.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Exceptions.RetrieveAllAccessPolicies.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Logic.RetrieveAllAccessPolicies.cs
- ISL.Providers.Storages.AzureBlobStorage/Providers/AzureBlobStorage/AzureBlobStorageProvider.cs
> PROVDERS: AzureBlobStorage RetrieveAllAccessPolicies

- ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.Exceptions.RetrieveAllContainers.cs
- ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.Logic.RetrieveAllContainers.cs
- ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.cs
- ISL.Providers.Storages.Abstractions/StorageAbstractionProvider.cs
> PROVIDERS: Azure StorageAbstractionProvder RetrieveAllContainers

- ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.Exceptions.DeleteContainer.cs
- ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.Logic.DeleteContainer.cs
- ISL.Providers.Storages.Abstractions/StorageAbstractionProvider.cs
> PROVIDERS: Azure StorageAbstractionProvider DeleteContainer

- ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.Exceptions.RemoveAccessPoliciesFromContainerAsync.cs
- ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.Logic.RemoveAccessPoliciesFromContainerAsync.cs
- ISL.Providers.Storages.Abstractions/IStorageOperations.cs
- ISL.Providers.Storages.Abstractions/StorageAbstractionProvider.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Acceptance/AzureBlobStorageProviderTests.RemoveAccessPolicies.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Acceptance/AzureBlobStorageProviderTests.RetrieveAccessPolicyByName.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Acceptance/AzureBlobStorageProviderTests.RetrieveAllAccessPolicies.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Acceptance/AzureBlobStorageProviderTests.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Exceptions.RemoveAccessPoliciesFromContainer.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Logic.RemoveAccessPoliciesFromContainer.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Storages/StorageTests.Exceptions.RemoveAccessPolicies.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Storages/StorageTests.Logic.RemoveAccessPolicies.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Storages/StorageTests.Validations.RemoveAccessPolicies.cs
- ISL.Providers.Storages.AzureBlobStorage/Brokers/Storages/Blobs/BlobStorageBroker.cs
- ISL.Providers.Storages.AzureBlobStorage/Brokers/Storages/Blobs/IBlobStorageBroker.cs
- ISL.Providers.Storages.AzureBlobStorage/Providers/AzureBlobStorage/AzureBlobStorageProvider.cs
- ISL.Providers.Storages.AzureBlobStorage/Services/Foundations/Storages/IStorageService.cs
- ISL.Providers.Storages.AzureBlobStorage/Services/Foundations/Storages/StorageService.cs
CLOSES #AB16514
CLOSES #AB18059
CLOSES #AB18060
> ACCEPTANCE: AzureBlobStorage Access policy tests

- ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.Exceptions.RemoveAllAccessPoliciesAsync.cs
- ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.Logic.RemoveAllAccessPoliciesAsync.cs
- ISL.Providers.Storages.Abstractions/IStorageOperations.cs
- ISL.Providers.Storages.Abstractions/StorageAbstractionProvider.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Acceptance/AzureBlobStorageProviderTests.RemoveAccessPolicies.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Exceptions.RemoveAllAccessPolicies.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Logic.RemoveAllAccessPolicies.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Storages/StorageTests.Exceptions.RemoveAccessPolicyByName.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Storages/StorageTests.Exceptions.RemoveAllAccessPolicies.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Storages/StorageTests.Logic.RemoveAccessPolicyByName.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Storages/StorageTests.Logic.RemoveAllAccessPolicies.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Storages/StorageTests.Validations.RemoveAccessPolicyByName.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Storages/StorageTests.Validations.RemoveAllAccessPolicies.cs
- ISL.Providers.Storages.AzureBlobStorage/Brokers/Storages/Blobs/BlobStorageBroker.cs
- ISL.Providers.Storages.AzureBlobStorage/Brokers/Storages/Blobs/IBlobStorageBroker.cs
- ISL.Providers.Storages.AzureBlobStorage/Providers/AzureBlobStorage/AzureBlobStorageProvider.cs
- ISL.Providers.Storages.AzureBlobStorage/Services/Foundations/Storages/IStorageService.cs
- ISL.Providers.Storages.AzureBlobStorage/Services/Foundations/Storages/StorageService.Exceptions.cs
- ISL.Providers.Storages.AzureBlobStorage/Services/Foundations/Storages/StorageService.Validations.cs
- ISL.Providers.Storages.AzureBlobStorage/Services/Foundations/Storages/StorageService.cs
> FOUNDATIONS: AzureBlobStorage RemoveAccessPolicyByName

- ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.Exceptions.RemoveAccessPolicyByNameAsync.cs
- ISL.Providers.Storages.Abstractions.Tests.Unit/StorageAbstractionProviderTests.Logic.RemoveAccessPolicyByName.cs
- ISL.Providers.Storages.Abstractions/StorageAbstractionProvider.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Exceptions.RemoveAccessPolicyByName.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Providers/AzureBlobStorage/AzureBlobStorageTests.Logic.RemoveAccessPolicyByName.cs
- ISL.Providers.Storages.AzureBlobStorage/Providers/AzureBlobStorage/AzureBlobStorageProvider.cs
> PROVIDERS AzureStorageProvider RemovePolicyByName

- .github/workflows/validatepr.yml
- ISL.Providers.Storages.AzureBlobStorage/Models/AzureBlobStoreConfigurations.cs
closes [AB#18415](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/18415)
> CODE RUB: Fixed model and updated validation script

- ISL.Providers.Storages.Abstractions/ISL.Providers.Storages.Abstractions.csproj
- ISL.Providers.Storages.AzureBlobStorage/ISL.Providers.Storages.AzureBlobStorage.csproj
closes [AB#18416](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/18416)
> RELEASES: v1.0.0.2

- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Storages/StorageTests.Validations.CreateFile.cs
- ISL.Providers.Storages.AzureBlobStorage.Tests.Unit/Services/Foundations/Storages/StorageTests.cs
- ISL.Providers.Storages.AzureBlobStorage/Services/Foundations/Storages/StorageService.Validations.cs
closes [AB#21291](https://dev.azure.com/NELAnalytics/LondonDataService/_workitems/edit/21291)
> CODE RUB: Allow empty files to be created
